### ISSUE TITLE
View user.details not found.

### ISSUE THREAD

**Issue by hecerinc** [ProyectoIntegrador2018/BlueMarket#152]
Can't access user details page.

## Repro

1. Sign in as any user
2. Go to `/users/{your_user_id}` (your user details page)

## Expected behavior

Expect to see the user details page.

## Actual behavior

Shows this instead:

![image](https://user-images.githubusercontent.com/7988472/55666251-3c3b9b00-5809-11e9-89f4-b626252c4364.png)

## Related

- Introduced in #148

**Comment by katiearriagam** [comment]
I think this is fixed with: #153
