### ISSUE TITLE
Cannot view a project's detail page

### ISSUE THREAD

**Issue by melytc** [ProyectoIntegrador2018/BlueMarket#168]
Cannot view a project's detail page.

## Conversation
Error: "Trying to get property of non-object" in line 46 (View: BlueMarket/resources/views/projects/details.blade.php)

## Repro
1. Sign in as teacher.
2. Go to `Projects` section.
3. Click on any project.
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/8518253/56061205-6243cc80-5d2e-11e9-9df3-128c62af745a.png">

## Expected behavior
When trying to view a project's details, the system should show the corresponding details view with the correct information. 

## Actual behavior
When trying to view a project's details, the system shows the Error Exception view with the following information:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/8518253/56061190-5bb55500-5d2e-11e9-98e6-a68460ea76d5.png">
 

## Related
- #26

**Comment by katiearriagam** [comment]
Fixed on #164 😄 good catch!
