### ISSUE TITLE
Design Specification Document

### ISSUE THREAD

**Issue by katiearriagam** [ProyectoIntegrador2018/BlueMarket#57]
Complete de Design Specification document

## Conversation
- [x] Complete all sections of the document (*use previous document of previous project as guidance*)
- [x] Data model 
- [x] Architecture: MVC but adds details to all of them
- [x] Collects wireframes in a single document
- [x] Reference to style guide URL (wherever it is deployed)
- [ ] UML artifacts as needed (optional)

## Acceptance criteria
- [x] Document is complete 
- [x] Document follows conventions as specified in the course material
- [x] Document is peer reviewed

**Comment by melytc** [comment]
Design Documentation Document can be found [here](https://docs.google.com/document/d/1zVAJCMgUhs7koxK3bkopi63FCffU6ZVgqfs-ulb8ouE/edit?usp=sharing).
