### ISSUE TITLE
Connect Project Creation Views & Controller.

### ISSUE THREAD

**Issue by anakarenbm** [ProyectoIntegrador2018/BlueMarket#71]
Juntar el front-end con el back-end de Register a Project.

**In order to do this. The following tasks should be completed:**

- [x] Model for Projects
- [x] Controller for Project (show, create)
- [x] Views for Project Creation 
- [x] Handle errors in front-end

**Comment by katiearriagam** [comment]
@anakarenbm @marcegarzab éste issue ya se puede cerrar, no?
