### ISSUE TITLE
HTTPS routing bug when using the navigation bar

### ISSUE THREAD

**Issue by osdagoso** [ProyectoIntegrador2018/BlueMarket#85]
"https" is removed after being redirected by a navbar button, causing unexpected site issues (e.g. Google Auth login button not appearing).

## Conversation
![image](https://user-images.githubusercontent.com/8510219/53775678-15f8a780-3eb9-11e9-9964-3e5030291c4b.png)

## How to reproduce
1. Go to the [current staging url](https://sheltered-hamlet-63420.herokuapp.com/).
2. Click on any link on the navbar (e.g. Login).

## Expected behavior
When navigating through the site using the navbar, all HTTP requests are redirected to HTTPS.

## Current behavior
When navigating through the site using the navbar, all HTTP requests are handled as such.

## Related user stories
- N/A

**Comment by katiearriagam** [comment]
Esto se ve más como un fix para backend. Lo platiqué con @hecerinc para ver cómo probarlo porque parece sólo fallar en el ambiente de producción (heroku).

cc: @osdagoso, @rubendelapena, @anakarenbm

Hay tres opciones para fix propuestos [aquí](https://www.kodementor.com/force-http-to-https-redirect-in-laravel/).
